import { CartItem } from './cartTypes';

export const mockCartItems: CartItem[] = [
  {
    id: '1',
    listingId: 'exp-1',
    listingType: 'experience',
    title: 'Pico: Explore, Recharge & Reconnect',
    subtitle: '3-day wellness retreat',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    rating: 4.9,
    reviewCount: 127,
    quantity: 1,
    selectedDate: new Date('2025-01-15'),
    selectedTime: '09:00',
    guests: {
      adults: 2,
      children: 0,
    },
    price: 180,
    pricePerUnit: 'Per person',
    currency: 'EUR',
    priceSnapshot: 180,
    discountAmount: 0,
    isRefundable: true,
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    createdAt: new Date(),
    updatedAt: new Date(),
    expiresAt: new Date(Date.now() + 10 * 60 * 1000), // 10 minutos
  },
  {
    id: '2',
    listingId: 'acc-1',
    listingType: 'accommodation',
    title: 'Casa Verde Ocean View',
    subtitle: 'Luxury villa with private pool',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400',
    rating: 4.8,
    reviewCount: 89,
    quantity: 1,
    selectedDate: new Date('2025-01-14'),
    guests: {
      adults: 3,
      children: 1,
    },
    price: 145,
    pricePerUnit: 'Per night',
    currency: 'EUR',
    priceSnapshot: 145,
    discountAmount: 0,
    isRefundable: false,
    cancellationPolicy: 'Non-refundable',
    createdAt: new Date(),
    updatedAt: new Date(),
    expiresAt: new Date(Date.now() + 10 * 60 * 1000),
  },
];
